### ISSUE TITLE
Transfer to personal account?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/data-packages#10]
@ateucher et al :wave: according to our [recently created package curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages) this repo should now be transferred to either one of your personal accounts, or the ropensci-archive organization.

If you don't answer within one month, I'll transfer the repository to ropensci-archive, after which you could still email me to transfer the repo to a personal account.

Thank you!

**Comment by ateucher** [comment]
Hi @maelle - I'm personally fine with it being transferred to the ropensci-archive org, though if someone else here wants it in their personal account, I'm fine with that too!

**Comment by maelle** [comment]
Thank you! I'll archive it, someone interested in taking it over could email me.
