### ISSUE TITLE
access to the google sheet

### ISSUE THREAD

**Issue by noamross** [ropenscilabs/data-packages#7]
Hi all! I'm doing a little data package project and was wondering of the Google Doc linked from the README could be opened - it is currently not public.

Also, quick question - were you able to figure out how many packages were data-only or primarily data?

**Comment by Nowosad** [comment]
Hi @noamross - I also do not have the access...
Regarding to your question, we were able to determine how many packages contains any data at all:
![](https://raw.githubusercontent.com/ropenscilabs/data-packages/master/README_files/figure-markdown_github/unnamed-chunk-1-1.png)

**Comment by ateucher** [comment]
If I remember correctly, I think the sheet was @richierocks' 🤔 (I also no longer have access)

**Comment by noamross** [comment]
Richie has re-opened the doc.
