### ISSUE TITLE
I love this project! I'm trying to update the Shiny and ran into a problem

### ISSUE THREAD

**Issue by jrosen48** [ropenscilabs/data-packages#9]
Hi all, I really love this project, and think it has a lot of potential for educators across the grade-range/contextual spectrum. I'm trying to update the Shiny and ran into a problem. Specifically, when running https://github.com/ropenscilabs/data-packages/blob/master/R/get-pkgs-with-data-dir.R, a _lot_ of packages were found, but the result indicated that no data directories were found, which of course can't be right:

<img width="498" alt="Screen Shot 2021-01-24 at 7 14 17 AM" src="https://user-images.githubusercontent.com/4596214/105629957-08819900-5e14-11eb-8b12-504bf7fcda33.png">

**Comment by ateucher** [comment]
Wow, so great to see this getting some interest again! 

Were you able to run the `map_df` chunk above that ([here](https://github.com/ropenscilabs/data-packages/blob/84e46256dcb5691c215dfab5f2a1c546ed9ea98a/R/get-pkgs-with-data-dir.R#L15-L53))? It takes a long time, so you might want to try with just the first 10 or so (e.g., on line 14 do `pkg_names <- rownames(ap)[1:10]`) to make sure it works...

**Comment by jrosen48** [comment]
thank you! I was able to run that. I think it ran fine - but, the `has_data_dir` column seemed to only have the value of `NA`. I may have run it incorrectly, but I thought it was on the right track - I saw (what appeared to be) all ~17,000 packages queried over a few hours.
